//演示数据
var data =
[
	{menuId:1,menuTitle:'MSN测试',menuLevel:10,page:'',icon:'02.gif',flag:0},
	//{menuId:2,menuTitle:'WEB IM',menuLevel:1001,page:'../../examples/weather/nl-robot.jsp',icon:'',flag:0},
	{menuId:2,menuTitle:'WEB IM',menuLevel:1001,page:'../../webim/index.htm',icon:'',flag:0},
	{menuId:3,menuTitle:'empAdd.jsp',menuLevel:1002,page:'../../page/samples/empAdd.jsp',icon:'',flag:0},
	{menuId:10,menuTitle:'开发工具',menuLevel:11,page:'',icon:'02.gif',flag:0},
	{menuId:11,menuTitle:'接口定义_原jsp页面',menuLevel:1101,page:'../../page/devtool/itf_define.jsp',icon:'',flag:0},
	{menuId:12,menuTitle:'接口定义',menuLevel:1102,page:'../../page/devtool/itf_define.htm',icon:'',flag:0},
	{menuId:13,menuTitle:'任务组列表(多请求)',menuLevel:1103,page:'../../page/test/taskGroupList.jsp',icon:'',flag:0},
	{menuId:14,menuTitle:'新增员工(多请求)',menuLevel:1104,page:'../../page/test/empAdd.jsp',icon:'',flag:0},
	{menuId:20,menuTitle:'KDF-BEX测试',menuLevel:20,page:'',icon:'01.gif',flag:0},
	{menuId:21,menuTitle:'查询-字典信息(LBM)',menuLevel:2003,page:'do?action=commonaction&funcId=11200001&rs=list&forward=result&zdmc=&zdbh=',icon:'',flag:0},
	{menuId:22,menuTitle:'查询-系统用户(IBatis)',menuLevel:2005,page:'do?action=commonaction&funcId=f_get_test_1&rs=list&forward=result',icon:'',flag:0},
	{menuId:23,menuTitle:'查询-系统菜单(Oracle)',menuLevel:2006,page:'do?action=commonaction&funcId=BSFUNC_001&rs=list&forward=result&kd_user_id=1',icon:'',flag:0},
	{menuId:24,menuTitle:'查询-用户登录(Bean)',menuLevel:2007,page:'do?action=commonaction&funcId=f_user_login&forward=result&P001=101&A006=202CB962AC59075B964B07152D234B70',icon:'',flag:0},
	{menuId:25,menuTitle:'查询-维度分类(XML)',menuLevel:2008,page:'do?action=commonaction&funcId=f20072000&rs=list&forward=result',icon:'',flag:0},
	{menuId:30,menuTitle:'KFCF测试',menuLevel:30,page:'',icon:'02.gif',flag:0},
	{menuId:31,menuTitle:'系统参数(CC)',menuLevel:3001,page:'../../page/sys/param_config.jsp',icon:'',flag:0},
	{menuId:32,menuTitle:'任务组列表(CC)',menuLevel:3002,page:'do?action=commonaction&funcId=28990001&rs=list&forward=list&p_gnbh=28990001&p_gybh=1&p_gymm=111111&rwzbh=-1&qylxbh=-1&szcsbh=-1&dwbh=-1',icon:'',flag:0},
	{menuId:31,menuTitle:'系统字典(CRM)',menuLevel:3003,page:'../../page/sys/dict_sys_list.jsp',icon:'',flag:0},
	{menuId:40,menuTitle:'AJAX测试',menuLevel:40,page:'',icon:'02.gif',flag:0},
	{menuId:42,menuTitle:'演示(AJAX)',menuLevel:4011,page:'../ajax/demo.htm',icon:'',flag:0},
	{menuId:51,menuTitle:'MOCK测试',menuLevel:50,page:'',icon:'01.gif',flag:0},
	{menuId:52,menuTitle:'查询-queryOrg(Mock)',menuLevel:5001,page:'cmd.do?funcId=10010001',icon:'',flag:0},
	{menuId:53,menuTitle:'新增-addOrg(Mock)',menuLevel:5002,page:'cmd.do?funcId=10010002',icon:'',flag:0},
	{menuId:54,menuTitle:'查询-员工信息(Mock)',menuLevel:5003,page:'do?action=employeeQuery&funcId=12200101&rs=list&forward=result',icon:'',flag:0},
	{menuId:60,menuTitle:'界面组件',menuLevel:60,page:'',icon:'01.gif',flag:0},
	{menuId:61,menuTitle:'dataGrid',menuLevel:6001,page:'../widget/dataGrid.htm',icon:'',flag:0},
	{menuId:62,menuTitle:'form',menuLevel:6002,page:'../widget/form.htm',icon:'',flag:0},
	{menuId:63,menuTitle:'dialog',menuLevel:6003,page:'../widget/dialog.htm',icon:'',flag:0},
	{menuId:64,menuTitle:'tabs',menuLevel:6004,page:'../widget/tabs.htm',icon:'',flag:0},
	{menuId:65,menuTitle:'tree',menuLevel:6005,page:'../widget/tree.htm',icon:'',flag:0}
];

//	{menuId:41,menuTitle:'查询-机构管理(AJAX)',menuLevel:4010,page:'../../ajax/dimen.htm',icon:'',flag:0},
